name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [20]
        rust: [stable]
    steps:
      - uses: actions/checkout@v4

      # 先安裝 pnpm（很關鍵，因為下面 setup-node 有 cache: 'pnpm' 會用到 pnpm）
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml

      - run: pnpm -C web install --frozen-lockfile
      - run: pnpm -C web build
      - run: pnpm -C web test

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      # ros2_demo 已從 workspace 拔出，不會被這條測到
      - run: cargo test --workspace --all-features
