name: CI (rust+web, no ROS)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Rust (bridge) ----------
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            crates/ros2_ws_bridge

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy -p ros2_ws_bridge -- -D warnings

      - name: Build bridge (release)
        run: cargo build -p ros2_ws_bridge --release

      # ---------- Web ----------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Install web deps
        run: pnpm -C web install --frozen-lockfile=false

      - name: Build web
        run: pnpm -C web build

      - name: Test web
        run: pnpm -C web test
